=== Kherdu/ABD/pr3_ADB/target/classes/Autores.dtd
<!ELEMENT autores (autor*)>
<!ELEMENT autor (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ATTLIST autor id ID #REQUIRED>

=== Kherdu/ABD/pr3_ADB/src/main/resources/Autores.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE autores SYSTEM "Autores.dtd">
<autores>
    <autor id="a01">
        <nombre>Abraham</nombre>
        <apellidos>Silberschatz</apellidos>
    </autor>
    <autor id="a02">
        <nombre>Henry F.</nombre>
        <apellidos>Korth</apellidos>
    </autor>
    <autor id="a03">
        <nombre>S.</nombre>
        <apellidos>Sudarshan</apellidos>
    </autor>
    <autor id="a04">
        <nombre>Thomas M.</nombre>
        <apellidos>Conolly</apellidos>
    </autor>
    <autor id="a05">
        <nombre>Carolyn E.</nombre>
        <apellidos>Begg</apellidos>
    </autor>
    <autor id="a06">
        <nombre>Priscilla</nombre>
        <apellidos>Walmsley</apellidos>
    </autor>
    <autor id="a07">
        <nombre>Peter Baer</nombre>
        <apellidos>Galvin</apellidos>
    </autor>
    <autor id="a08">
        <nombre>Greg</nombre>
        <apellidos>Gagne</apellidos>
    </autor>
    <autor id="a09">
        <nombre>Joe</nombre>
        <apellidos>Fawcett</apellidos>
    </autor>
</autores>
