=== Kherdu/ABD/pr3_ADB/src/main/resources/Contactos.dtd
<!ELEMENT agenda (contacto)+>
<!ELEMENT contacto (nombre, apellidos, direcci贸n?, telefono*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT direcci贸n (calle, numero, c贸digo-postal, localidad)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT c贸digo-postal (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (casa | trabajo | movil) #REQUIRED>
<!ATTLIST contacto dni CDATA #REQUIRED>

=== Kherdu/ABD/pr3_ADB/target/classes/Contactos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "Contactos.dtd">
<agenda> 
   <contacto dni="51233412H">
      <nombre>David</nombre>
      <apellidos>Álvez Campos</apellidos>
      <dirección>
         <calle>Paseo de Ondarreta</calle>
         <numero>5</numero>
         <código-postal>20018</código-postal>
         <localidad>San Sebastián</localidad>	
      </dirección>
      <telefono tipo="casa">943102321</telefono>
      <telefono tipo="movil">617702341</telefono>
      <telefono tipo="trabajo">23122123</telefono>
   </contacto>

   <contacto dni="46821354T">
      <nombre>Víctor</nombre>
      <apellidos>Martín Moreno</apellidos>
      <telefono tipo="casa">914621100</telefono>
   </contacto>
</agenda>
